[package]
name = "filite"
version = "0.2.0"
authors = ["Raphaël Thériault <raphael_theriault@outlook.com>"]
edition = "2018"
description = "A simple, light and standalone pastebin, URL shortener and file-sharing service"
homepage = "https://github.com/raftario/filite"
repository = "https://github.com/raftario/filite"
readme = "README.md"
keywords = [
    "file-sharing",
    "url-shortener",
    "pastebin"
]
license = "MIT"

[dependencies]
actix-files = "0.1.6"
actix-identity = "0.1.0"
actix-web = "1.0.8"
base64 = "0.11.0"
blake2 = "0.8.1"
chrono = "0.4.9"
diesel_migrations = "1.4.0"
dirs = "2.0.2"
dotenv = { version = "0.15.0", optional = true }
env_logger = "0.7.1"
futures = "0.1.29"
lazy_static = "1.4.0"
num_cpus = "1.10.1"
toml = "0.5.3"
[dependencies.diesel]
version = "1.4.3"
features = ["r2d2", "sqlite"]
[dependencies.libsqlite3-sys]
version = "0.16.0"
features = ["bundled"]
[dependencies.serde]
version = "1.0.102"
features = ["derive"]

[features]
default = []
dev = ["dotenv"]
